# Generated by Django 4.2.9 on 2026-05-20 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['business__name', 'role'], 'verbose_name': 'Membresía', 'verbose_name_plural': 'Membresías'},
        ),
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('RETAIL', 'Retail/Tienda'), ('RESTAURANT', 'Restaurante'), ('SERVICE', 'Servicios'), ('MANUFACTURING', 'Manufactura'), ('OTHER', 'Otro')], default='RETAIL', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('MANAGER', 'Gerente'), ('VENDEDOR', 'Vendedor'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='business',
            table=None,
        ),
        migrations.AlterModelTable(
            name='membership',
            table=None,
        ),
    ]
