# Generated by Django 4.2.9 on 2026-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='slug',
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(default='RETAIL', max_length=20),
        ),
    ]
