# Generated by Django 4.2.9 on 2026-05-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
