# Generated by Django 4.2.9 on 2026-05-29 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_membership_permissions_alter_membership_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_roles', '0002_businessrole_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Empleado')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario del Negocio',
                'verbose_name_plural': 'Usuarios del Negocio',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('user', 'business')},
            },
        ),
        migrations.CreateModel(
            name='BusinessUserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='business_roles.businessuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='business_roles.businessrole')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Rol',
                'ordering': ['-assigned_at'],
                'unique_together': {('business_user', 'role', 'is_active')},
            },
        ),
    ]
