# Generated by Django 4.2.9 on 2026-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_roles', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usiness_roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='business_roles.businessrole', verbose_name='Roles de Negocio'),
        ),
    ]
